-- vim.pack.add({ "https://github.com/haoming-li-ling/nvim-jump" })
vim.pack.add({ "file:///Users/haomingli/repos/nvim-jump" })
require("jump").setup({
  disable_conceal = true,
})
vim.keymap.set("n", "s", function()
  require("jump").start()
end)
vim.keymap.set({ "x", "o" }, "z", function()
  require("jump").start()
end)
vim.keymap.set({ "x", "o" }, "t", function()
  require("jump").start({ operator_mode = "exclusive" })
end)
vim.keymap.set({ "x", "o" }, "f", function()
  require("jump").start({ operator_mode = "inclusive" })
end)
