-- vim.pack.add({
--   "https://github.com/nvim-neorg/neorg",
--   "https://github.com/nvim-lua/plenary.nvim",
--   "https://github.com/nvim-neorg/neorg-telescope",
--   "https://github.com/benlubas/neorg-interim-ls",
--   "https://github.com/nvim-telescope/telescope.nvim",
-- })
--
-- vim.keymap.set("n", "<leader>nrf", function()
--   vim.cmd([[Neorg workspace notes]])
--   -- vim.cmd([[Telescope find_files cwd=/Users/haomingli/Documents/neorg/notes]])
--   Snacks.picker.files({ cwd = "/Users/haomingli/Documents/neorg/notes" })
-- end, { desc = "Find notes" })
-- vim.keymap.set("n", "<leader>nrm", "<cmd>Neorg inject-metadata<cr>", { desc = "Inject metadata" })
-- vim.keymap.set("n", "<leader>nwn", "<cmd>Neorg workspace notes<cr>", { desc = "Workspace notes" })
--
-- require("neorg").setup({
--   load = {
--     ["core.autocommands"] = {},
--     ["core.completion"] = {
--       config = {
--         engine = {
--           module_name = "external.lsp-completion",
--         },
--       },
--     },
--     ["core.concealer"] = {
--       config = {
--         dim_code_blocks = {
--           conceal = false,
--         },
--       },
--     },
--     ["core.defaults"] = {},
--     ["core.dirman"] = {
--       config = {
--         workspaces = {
--           notes = "~/Documents/neorg/notes",
--         },
--       },
--     },
--     ["core.esupports.metagen"] = {
--       config = {
--         update_date = false,
--       },
--     },
--     ["core.export"] = {
--       config = {},
--     },
--     ["core.export.markdown"] = {
--       config = {},
--     },
--     ["core.integrations.treesitter"] = {
--       config = {},
--     },
--     ["core.journal"] = {},
--     ["core.keybinds"] = {
--       config = {
--         default_keybinds = true,
--         neorg_leader = "<leader>",
--       },
--     },
--     ["core.neorgcmd"] = {},
--     ["core.qol.todo_items"] = {
--       config = {
--         create_todo_items = true,
--         create_todo_parents = true,
--       },
--     },
--     ["core.summary"] = {},
--     ["core.ui"] = {},
--     ["external.interim-ls"] = {
--       config = {
--         completion_provider = {
--           categories = false,
--           documentation = true,
--           enable = true,
--           people = {
--             enable = false,
--             path = "people",
--           },
--         },
--       },
--     },
--   },
-- })
