-- vim.pack.add({
--   "https://github.com/folke/noice.nvim",
--   "https://github.com/MunifTanjim/nui.nvim",
--   "https://github.com/rcarriga/nvim-notify",
-- })
--
-- require("noice").setup({
--   lsp = {
--     override = {
--       ["cmp.entry.get_documentation"] = true,
--       ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--       ["vim.lsp.util.stylize_markdown"] = true,
--     },
--     progress = {
--       enabled = true,
--       format = {
--         "({data.progress.percentage}%) ",
--         {
--           "{spinner} ",
--           hl_group = "NoiceLspProgressSpinner",
--         },
--         {
--           "{data.progress.title} ",
--           hl_group = "NoiceLspProgressTitle",
--         },
--         {
--           "{data.progress.client} ",
--           hl_group = "NoiceLspProgressClient",
--         },
--       },
--     },
--   },
--   messages = {
--     enabled = true,
--   },
--   presets = {
--     bottom_search = true,
--     command_palette = true,
--     inc_rename = true,
--     long_message_to_split = true,
--     lsp_doc_border = true,
--   },
--   routes = {
--     {
--       filter = {
--         any = {
--           {
--             find = "%d+L, %d+B",
--           },
--           {
--             find = "; after #%d+",
--           },
--           {
--             find = "; before #%d+",
--           },
--         },
--         event = "msg_show",
--       },
--       view = "mini",
--     },
--   },
-- })
