vim.pack.add({
  "https://github.com/mrjones2014/smart-splits.nvim",
})
require("smart-splits").setup({
  at_edge = "stop",
})
vim.keymap.set({ "n", "x", "t" }, "<C-h>", function()
  require("smart-splits").move_cursor_left()
end)
vim.keymap.set({ "n", "x", "t" }, "<C-j>", function()
  require("smart-splits").move_cursor_down()
end)
vim.keymap.set({ "n", "x", "t" }, "<C-k>", function()
  require("smart-splits").move_cursor_up()
end)
vim.keymap.set({ "n", "x", "t" }, "<C-l>", function()
  require("smart-splits").move_cursor_right()
end)
vim.keymap.set("n", "<C-\\>", function()
  require("smart-splits").move_cursor_previous()
end)
vim.keymap.set("n", "<leader><leader>h", function()
  require("smart-splits").swap_buf_left()
end)
vim.keymap.set("n", "<leader><leader>j", function()
  require("smart-splits").swap_buf_down()
end)
vim.keymap.set("n", "<leader><leader>k", function()
  require("smart-splits").swap_buf_up()
end)
vim.keymap.set("n", "<leader><leader>l", function()
  require("smart-splits").swap_buf_right()
end)
