-- vim.pack.add({
--   "https://github.com/gbprod/yanky.nvim",
--   "https://github.com/kkharji/sqlite.lua",
-- })
--
-- require("yanky").setup({
--   highlight = { timer = 200 },
--   ring = { storage = "sqlite" },
--   -- picker = {},
-- })
--
-- vim.keymap.set({ "n", "x" }, "y", "<Plug>(YankyYank)", { desc = "Yank text" })
-- vim.keymap.set({ "n", "x" }, "Y", "<Plug>(YankyYank)$", { desc = "Yank to end of line" })
-- vim.keymap.set({ "n", "x" }, "p", "<Plug>(YankyPutAfter)", { desc = "Put yanked text after cursor" })
-- vim.keymap.set({ "n", "x" }, "P", "<Plug>(YankyPutBefore)", { desc = "Put yanked text before cursor" })
-- vim.keymap.set({ "n", "x" }, "\\p", "<Plug>(YankyPutAfterLinewise)", { desc = "Put yanked text on the next line" })
-- vim.keymap.set({ "n", "x" }, "\\P", "<Plug>(YankyPutBeforeLinewise)", { desc = "Put yanked text on the previous line" })
-- vim.keymap.set({ "n", "x" }, "gp", "<Plug>(YankyGPutAfter)", { desc = "Put yanked text after selection" })
-- vim.keymap.set({ "n", "x" }, "gP", "<Plug>(YankyGPutBefore)", { desc = "Put yanked text before selection" })
-- vim.keymap.set("n", "<c-f>", "<Plug>(YankyCycleForward)", { desc = "Cycle forward through yank history" })
-- vim.keymap.set("n", "<c-b>", "<Plug>(YankyCycleBackward)", { desc = "Cycle backward through yank history" })
-- vim.keymap.set("n", "[y", "<Plug>(YankyCycleForward)", { desc = "Cycle forward through yank history" })
-- vim.keymap.set("n", "]y", "<Plug>(YankyCycleBackward)", { desc = "Cycle backward through yank history" })
-- vim.keymap.set("n", "]p", "<Plug>(YankyPutIndentAfterLinewise)", { desc = "Put indented after cursor (linewise)" })
-- vim.keymap.set("n", "[p", "<Plug>(YankyPutIndentBeforeLinewise)", {
--   desc = "Put indented before cursor (linewise)",
-- })
-- vim.keymap.set("n", "]P", "<Plug>(YankyPutIndentAfterLinewise)", { desc = "Put indented after cursor (linewise)" })
-- vim.keymap.set("n", "[P", "<Plug>(YankyPutIndentBeforeLinewise)", {
--   desc = "Put indented before cursor (linewise)",
-- })
-- vim.keymap.set("n", ">p", "<Plug>(YankyPutIndentAfterShiftRight)", { desc = "Put and indent right" })
-- vim.keymap.set("n", "<p", "<Plug>(YankyPutIndentAfterShiftLeft)", { desc = "Put and indent left" })
-- vim.keymap.set("n", ">P", "<Plug>(YankyPutIndentBeforeShiftRight)", { desc = "Put before and indent right" })
-- vim.keymap.set("n", "<P", "<Plug>(YankyPutIndentBeforeShiftLeft)", { desc = "Put before and indent left" })
-- vim.keymap.set("n", "=p", "<Plug>(YankyPutAfterFilter)", { desc = "Put after applying a filter" })
-- vim.keymap.set("n", "=P", "<Plug>(YankyPutBeforeFilter)", { desc = "Put before applying a filter" })
